export const FETCH_PRODUCTS_DATA_REQ = "FETCH_PRODUCTS_DATA_REQ";
export const FETCH_PRODUCTS_DATA_SUC = "FETCH_PRODUCTS_DATA_SUC";
export const FETCH_PRODUCTS_DATA_FAIL = "FETCH_PRODUCTS_DATA_FAIL";

export const FETCH_ONE_USER_BY_ID_SUC = "FETCH_ONE_USER_BY_ID_SUC";
