export const FETCH_PRODUCTS_DATA_REQ = "FETCH_PRODUCTS_DATA_REQ";
export const FETCH_PRODUCTS_DATA_SUC = "FETCH_PRODUCTS_DATA_SUC";
export const FETCH_PRODUCTS_DATA_FAIL = "FETCH_PRODUCTS_DATA_FAIL";

export const FETCH_ONE_USER_BY_ID_SUC = "FETCH_ONE_USER_BY_ID_SUC";
export const SORT_DATA_REQ = "SORT_DATA_REQ";
export const SORT_DATA_SUC = "SORT_DATA_SUC";

export const DELETE_ONE_USER_SUC = "DELETE_ONE_USER_SUC";
export const DELETE_ONE_USER_REQ = "DELETE_ONE_USER_REQ";

export const EDIT_ONE_USER_REQ = "EDIT_ONE_USER_REQ";
export const EDIT_ONE_USER_SUC = "EDIT_ONE_USER_SUC";
